name: MinIO Action
description: Runs MinIO server in a GitHub workflow
author: Changkyun Kim
branding:
  icon: upload-cloud
  color: blue
inputs:
  access_key:
    description: Access key ID for MinIO server
    required: true
    default: minio
  secret_key:
    description: Secret access key for MinIO server
    required: true
    default: minio
  port:
    description: Port number for MinIO server
    required: false
    default: '9000'
  bucket_name:
    description: Create a bucket with the given name
    required: false
runs:
  env:
    MINIO_ACCESS_KEY: ${{ inputs.access_key }}
    MINIO_SECRET_KEY: ${{ inputs.secret_key }}
    PORT: ${{ inputs.port }}
  using: docker
  image: Dockerfile
  entrypoint: /entrypoint.sh
  post-entrypoint: |
    if [ -n "$BUCKET_NAME" ]; then
      echo "Creating bucket $BUCKET_NAME"
      export AWS_ACCESS_KEY_ID=$MINIO_ACCESS_KEY
      export AWS_SECRET_ACCESS_KEY=$MINIO_SECRET_KEY
      export AWS_EC2_METADATA_DISABLED=true
      aws --endpoint-url http://127.0.0.1:$PORT s3 mb s3://$BUCKET_NAME
    fi
